# Generated by scripts/extract_pvrig_interface.py
# Executable PyMOL helper. It uses raw PDB residue numbers per structure; consensus is derived from alignment columns.
load data/structures/8X6B.pdb, pdb8x6b
hide everything, pdb8x6b
show cartoon, pdb8x6b and chain B
show surface, pdb8x6b and chain B
color gray80, pdb8x6b and chain B
select pvrig_8X6B_all, pdb8x6b and chain B and resi 33+34+36+43+44+45+49+52+54+57+58+59+60+62+97+99+100+101+102+103+104+105+106
color yellow, pvrig_8X6B_all
show sticks, pvrig_8X6B_all
select pvrig_8X6B_consensus, pdb8x6b and chain B and resi 33+34+36+43+44+45+52+54+57+58+60+62+97+99+100+101+102+103+104+105+106
color orange, pvrig_8X6B_consensus
show sticks, pvrig_8X6B_consensus
select pvrig_8X6B_single_structure, pdb8x6b and chain B and resi 49+59
color tv_yellow, pvrig_8X6B_single_structure
show sticks, pvrig_8X6B_single_structure

load data/structures/9E6Y.pdb, pdb9e6y
hide everything, pdb9e6y
show cartoon, pdb9e6y and chain A
show surface, pdb9e6y and chain A
color gray80, pdb9e6y and chain A
select pvrig_9E6Y_all, pdb9e6y and chain A and resi 31+32+34+41+42+43+47+50+52+55+56+57+58+60+95+97+98+99+100+101+102+103+104
color yellow, pvrig_9E6Y_all
show sticks, pvrig_9E6Y_all
select pvrig_9E6Y_consensus, pdb9e6y and chain A and resi 31+32+34+41+42+43+50+52+55+56+58+60+95+97+98+99+100+101+102+103+104
color orange, pvrig_9E6Y_consensus
show sticks, pvrig_9E6Y_consensus
select pvrig_9E6Y_single_structure, pdb9e6y and chain A and resi 47+57
color tv_yellow, pvrig_9E6Y_single_structure
show sticks, pvrig_9E6Y_single_structure

set transparency, 0.35
zoom pvrig_8X6B_consensus or pvrig_9E6Y_consensus
# Soft hints S67/R95/I97 are intentionally not selected here; see PVRIG_soft_hint_structure_mapping.csv after numbering reconciliation.
