#!/usr/bin/env python3
"""Write a compact, repository-visible snapshot of the latest lightweight sync."""
from __future__ import annotations

import argparse
import subprocess
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path


def git_output(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--manifest", default="docs/lightweight_sync_manifest.txt")
    parser.add_argument("--output", default="docs/LIGHTWEIGHT_SYNC_STATUS.md")
    parser.add_argument("--synced-at", default=datetime.now().astimezone().isoformat(timespec="seconds"))
    args = parser.parse_args()

    root = Path(args.root).resolve()
    manifest = root / args.manifest
    output = root / args.output
    paths = [line for line in manifest.read_text(encoding="utf-8").splitlines() if line]
    if args.output not in paths:
        paths.append(args.output)

    counts: Counter[str] = Counter()
    sizes: defaultdict[str, int] = defaultdict(int)
    total_bytes = 0
    existing_count = 0
    for rel in sorted(set(paths)):
        path = root / rel
        if path == output and not path.exists():
            continue
        try:
            size = path.stat().st_size
        except OSError:
            continue
        top = rel.split("/", 1)[0] if "/" in rel else "."
        counts[top] += 1
        sizes[top] += size
        total_bytes += size
        existing_count += 1

    branch = git_output(root, "rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    head = git_output(root, "rev-parse", "--short=12", "HEAD") or "unknown"
    remote = git_output(root, "remote", "get-url", "origin") or "unknown"

    lines = [
        "# Lightweight Sync Status",
        "",
        "> Auto-generated by `scripts/update_lightweight_sync_status.py`; do not edit manually.",
        "",
        f"- Last content sync: `{args.synced_at}`",
        f"- Branch: `{branch}`",
        f"- Base HEAD before this sync commit: `{head}`",
        f"- Remote: `{remote}`",
        f"- Manifest-selected existing files: `{existing_count}`",
        f"- Approximate selected size: `{total_bytes / 1024 / 1024:.2f} MiB`",
        "",
        "## Included By Top-Level Area",
        "",
        "| Area | Files | Size MiB |",
        "| --- | ---: | ---: |",
    ]
    for top in sorted(counts, key=lambda name: (-sizes[name], name)):
        lines.append(f"| `{top}` | {counts[top]:,} | {sizes[top] / 1024 / 1024:.2f} |")
    lines += [
        "",
        "## Runtime",
        "",
        "- Automatic sync control: `scripts/lightweight_sync_daemon.sh status`",
        "- Exact tracked allowlist: `docs/lightweight_sync_manifest.txt`",
        "- Selection policy and exclusions: `docs/LIGHTWEIGHT_SYNC_INVENTORY.md`",
        "- Runtime logs/state stay under local `.omx/` and are not committed.",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
