# Curated manifest for nanobody/VHH tool survey assets.
# `pdf_urls` are open-access candidates only; downloader verifies PDF content.
TOOLS = [
    # Structure / complex prediction
    dict(id='nanobodybuilder2_immunebuilder', category='structure', name='NanoBodyBuilder2 / ImmuneBuilder',
         papers=['https://www.nature.com/articles/s42003-023-04927-7'],
         pdf_urls=['https://www.nature.com/articles/s42003-023-04927-7.pdf'],
         code_urls=['https://github.com/oxpig/ImmuneBuilder']),
    dict(id='nanonet', category='structure', name='NanoNet',
         papers=['https://www.frontiersin.org/articles/10.3389/fimmu.2022.958584/full'],
         pdf_urls=['https://www.frontiersin.org/articles/10.3389/fimmu.2022.958584/pdf'],
         code_urls=['https://github.com/dina-lab3D/NanoNet']),
    dict(id='igfold', category='structure', name='IgFold',
         papers=['https://www.nature.com/articles/s41467-023-38063-x'],
         pdf_urls=['https://www.nature.com/articles/s41467-023-38063-x.pdf'],
         code_urls=['https://github.com/Graylab/IgFold']),
    dict(id='heavybuilder2', category='structure', name='HeavyBuilder2',
         papers=['https://www.sciencedirect.com/science/article/pii/S0022283625005753'],
         pdf_urls=[], code_urls=['https://github.com/oxpig/HeavyBuilder2']),
    dict(id='abodybuilder3', category='structure', name='ABodyBuilder3',
         papers=['https://academic.oup.com/bioinformatics/article/40/10/btae576/7810444'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/40/10/btae576/59571994/btae576.pdf'],
         code_urls=['https://github.com/exscientia/abodybuilder3']),
    dict(id='deepab', category='structure', name='DeepAb',
         papers=['https://www.sciencedirect.com/science/article/pii/S2666389921002804'],
         pdf_urls=[], code_urls=['https://github.com/RosettaCommons/DeepAb']),
    dict(id='ablooper', category='structure', name='ABlooper',
         papers=['https://academic.oup.com/bioinformatics/article/38/7/1877/6517780'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/38/7/1877/43598388/btac016.pdf'],
         code_urls=['https://github.com/oxpig/ABlooper']),
    dict(id='h3_opt', category='structure', name='H3-OPT',
         papers=['https://elifesciences.org/articles/91512'],
         pdf_urls=['https://elifesciences.org/articles/91512.pdf'],
         code_urls=['https://github.com/chenhd21/H3-OPT']),
    dict(id='rosetta_snugdock', category='structure', name='RosettaAntibody3 / SnugDock',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC7993800/','https://docs.rosettacommons.org/docs/latest/application_documentation/antibody/antibody-protocol'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC7993800/pdf/'],
         code_urls=[]),
    dict(id='alphafold3', category='structure', name='AlphaFold 3 / AlphaFold Server',
         papers=['https://www.nature.com/articles/s41586-024-07487-w','https://alphafoldserver.com/'],
         pdf_urls=['https://www.nature.com/articles/s41586-024-07487-w.pdf'],
         code_urls=['https://github.com/google-deepmind/alphafold3']),
    dict(id='colabfold_alphafold_multimer', category='structure', name='AlphaFold-Multimer / ColabFold',
         papers=['https://www.nature.com/articles/s41592-022-01488-1'],
         pdf_urls=['https://www.nature.com/articles/s41592-022-01488-1.pdf'],
         code_urls=['https://github.com/sokrypton/ColabFold','https://github.com/google-deepmind/alphafold']),
    dict(id='chai1', category='structure', name='Chai-1',
         papers=['https://www.biorxiv.org/content/10.1101/2024.10.10.615955v2'],
         pdf_urls=['https://www.biorxiv.org/content/10.1101/2024.10.10.615955v2.full.pdf'],
         code_urls=['https://github.com/chaidiscovery/chai-lab']),
    dict(id='boltz', category='structure', name='Boltz-1 / Boltz-2',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC11601547/'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC11601547/pdf/'],
         code_urls=['https://github.com/jwohlwend/boltz']),
    dict(id='haddock3', category='structure', name='HADDOCK2.4 / HADDOCK3',
         papers=['https://www.bonvinlab.org/education/HADDOCK3/HADDOCK3-nanobody-antigen/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11483107/'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC11483107/pdf/'],
         code_urls=['https://github.com/haddocking/haddock3','https://github.com/haddocking/HADDOCK-antibody-antigen']),
    dict(id='cluspro_abemap', category='structure', name='ClusPro / AbEMap',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC10898366/','https://cluspro.org/help.php'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC10898366/pdf/'], code_urls=[]),
    dict(id='hdock', category='structure', name='HDOCK',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC5793843/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC5793843/pdf/'], code_urls=[]),
    dict(id='balmfold', category='structure', name='BALMFold',
         papers=['https://academic.oup.com/bib/article/25/4/bbae245/7682462'],
         pdf_urls=['https://academic.oup.com/bib/article-pdf/25/4/bbae245/57988258/bbae245.pdf'],
         code_urls=['https://github.com/beam-labs/balm']),
    dict(id='abdockgen', category='structure', name='AbDockGen',
         papers=['https://proceedings.mlr.press/v162/jin22a.html'],
         pdf_urls=['https://proceedings.mlr.press/v162/jin22a/jin22a.pdf'],
         code_urls=['https://github.com/wengong-jin/abdockgen']),
    dict(id='deeprank_ab', category='structure', name='DeepRank-Ab',
         papers=['https://github.com/haddocking/DeepRank-Ab'], pdf_urls=[], code_urls=['https://github.com/haddocking/DeepRank-Ab']),

    # Design
    dict(id='rfantibody', category='design', name='RFantibody',
         papers=['https://www.nature.com/articles/s41586-025-09721-5','https://www.bakerlab.org/2025/02/28/designing-antibodies-with-rfdiffusion/'],
         pdf_urls=['https://www.nature.com/articles/s41586-025-09721-5.pdf'],
         code_urls=['https://github.com/RosettaCommons/RFantibody']),
    dict(id='nanodesigner', category='design', name='NanoDesigner',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC12333243/'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC12333243/pdf/'],
         code_urls=['https://github.com/bio-ontology-research-group/NanoDesigner']),
    dict(id='germinal', category='design', name='Germinal',
         papers=['https://www.biorxiv.org/content/10.1101/2025.09.19.677421v1'],
         pdf_urls=['https://www.biorxiv.org/content/10.1101/2025.09.19.677421v1.full.pdf'],
         code_urls=['https://github.com/SantiagoMille/germinal']),
    dict(id='iggm', category='design', name='IgGM',
         papers=['https://openreview.net/forum?id=zmmfsJpYcq','https://proceedings.iclr.cc/paper_files/paper/2025/hash/fa5b423e24b442180bcd4e13ae75a27f-Abstract-Conference.html'],
         pdf_urls=['https://openreview.net/pdf?id=zmmfsJpYcq'],
         code_urls=['https://github.com/TencentAI4S/IgGM']),
    dict(id='tfdesign_sdab', category='design', name='TFDesign-sdAb',
         papers=['https://www.nature.com/articles/s41421-025-00843-8'],
         pdf_urls=['https://www.nature.com/articles/s41421-025-00843-8.pdf'], code_urls=[]),
    dict(id='chai2', category='design', name='Chai-2',
         papers=['https://www.biorxiv.org/content/10.1101/2025.07.05.663018v1.full-text'],
         pdf_urls=['https://www.biorxiv.org/content/10.1101/2025.07.05.663018v1.full.pdf'], code_urls=[]),
    dict(id='latentx2', category='design', name='Latent-X2',
         papers=['https://arxiv.org/abs/2512.20263'], pdf_urls=['https://arxiv.org/pdf/2512.20263'], code_urls=[]),
    dict(id='jam2', category='design', name='JAM-2',
         papers=['https://nabla-public.s3.us-east-1.amazonaws.com/2025_Nabla_JAM2.pdf'],
         pdf_urls=['https://nabla-public.s3.us-east-1.amazonaws.com/2025_Nabla_JAM2.pdf'], code_urls=[]),
    dict(id='easynano', category='design', name='EasyNano',
         papers=['https://arxiv.org/abs/2606.12772'], pdf_urls=['https://arxiv.org/pdf/2606.12772'], code_urls=[]),
    dict(id='diffab', category='design', name='DiffAb',
         papers=['https://openreview.net/forum?id=jSorGn2Tjg'], pdf_urls=['https://openreview.net/pdf?id=jSorGn2Tjg'],
         code_urls=['https://github.com/luost26/diffab']),
    dict(id='antifold', category='design', name='AntiFold',
         papers=['https://arxiv.org/abs/2405.03370','https://opig.stats.ox.ac.uk/webapps/antifold/'],
         pdf_urls=['https://arxiv.org/pdf/2405.03370'], code_urls=['https://github.com/oxpig/AntiFold']),
    dict(id='nanofold', category='design', name='nanoFOLD',
         papers=['https://www.biorxiv.org/content/10.1101/2025.04.29.651236v1'],
         pdf_urls=['https://www.biorxiv.org/content/10.1101/2025.04.29.651236v1.full.pdf'], code_urls=[]),
    dict(id='iglm', category='design', name='IgLM',
         papers=['https://www.sciencedirect.com/science/article/pii/S2405471223002715'],
         pdf_urls=[], code_urls=['https://github.com/Graylab/IgLM']),
    dict(id='vhhbert', category='design', name='VHHBERT / VHHCorpus-2M',
         papers=['https://arxiv.org/abs/2405.18749'], pdf_urls=['https://arxiv.org/pdf/2405.18749'],
         code_urls=['https://github.com/cognano/AVIDa-SARS-CoV-2']),
    dict(id='abnativ', category='design', name='AbNatiV / AbNatiV2',
         papers=['https://www.nature.com/articles/s42256-023-00778-3'], pdf_urls=['https://www.nature.com/articles/s42256-023-00778-3.pdf'],
         code_urls=['https://gitlab.doc.ic.ac.uk/sormanni-lab/abnativ']),
    dict(id='hudiff', category='design', name='HuDiff / HuDiff-Nb',
         papers=['https://www.biorxiv.org/content/10.1101/2024.10.22.619416v1'],
         pdf_urls=['https://www.biorxiv.org/content/10.1101/2024.10.22.619416v1.full.pdf'],
         code_urls=['https://github.com/TencentAI4S/HuDiff']),
    dict(id='llamanade', category='design', name='Llamanade',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC8351782/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC8351782/pdf/'], code_urls=[]),
    dict(id='biophi', category='design', name='BioPhi / Sapiens / OASis',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC8837241/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC8837241/pdf/'],
         code_urls=['https://github.com/merck/biophi','https://github.com/Merck/Sapiens']),
    dict(id='humatch', category='design', name='Humatch',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC11610552/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC11610552/pdf/'],
         code_urls=['https://github.com/oxpig/Humatch']),
    dict(id='igcraft', category='design', name='IgCraft',
         papers=['https://arxiv.org/abs/2503.19821'], pdf_urls=['https://arxiv.org/pdf/2503.19821'], code_urls=['https://github.com/mgreenig/igcraft']),
    dict(id='mcsm_ab2', category='design', name='mCSM-AB2',
         papers=['https://academic.oup.com/bioinformatics/article/36/5/1453/5607734'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/36/5/1453/32619347/btz752.pdf'], code_urls=[]),
    dict(id='gearbind', category='design', name='GearBind',
         papers=['https://www.nature.com/articles/s41467-024-51563-8'], pdf_urls=['https://www.nature.com/articles/s41467-024-51563-8.pdf'],
         code_urls=['https://github.com/DeepGraphLearning/GearBind']),
    dict(id='graphinity', category='design', name='Graphinity',
         papers=['https://github.com/oxpig/Graphinity'], pdf_urls=[], code_urls=['https://github.com/oxpig/Graphinity']),

    # Identification / discovery
    dict(id='alpseq', category='identification', name='alpseq',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC12885427/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC12885427/pdf/'],
         code_urls=['https://github.com/kzeglinski/alpseq']),
    dict(id='nanomap', category='identification', name='NanoMAP',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC13001438/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC13001438/pdf/'],
         code_urls=['https://github.com/wlwhite-tufts/NanoMAP']),
    dict(id='phage_seq_nbseq', category='identification', name='phage-seq + nbseq',
         papers=['https://github.com/caseygrun/phage-seq','https://github.com/caseygrun/nbseq'], pdf_urls=[],
         code_urls=['https://github.com/caseygrun/phage-seq','https://github.com/caseygrun/nbseq']),
    dict(id='anarci', category='identification', name='ANARCI',
         papers=['https://academic.oup.com/bioinformatics/article/32/2/298/1744206'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/32/2/298/17011140/btv552.pdf'],
         code_urls=['https://github.com/oxpig/ANARCI']),
    dict(id='igblast', category='identification', name='IgBLAST',
         papers=['https://www.ncbi.nlm.nih.gov/igblast/'], pdf_urls=[], code_urls=[]),
    dict(id='mixcr', category='identification', name='MiXCR',
         papers=['https://github.com/milaboratory/mixcr','https://mixcr.com/mixcr/reference/overview-analysis-overview/'], pdf_urls=[],
         code_urls=['https://github.com/milaboratory/mixcr']),
    dict(id='immcantation', category='identification', name='Immcantation / pRESTO / Change-O / airrflow',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC4793929/','https://immcantation.readthedocs.io/'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC4793929/pdf/'],
         code_urls=['https://github.com/immcantation/presto','https://github.com/immcantation/changeo','https://github.com/nf-core/airrflow']),
    dict(id='igdiscover', category='identification', name='IgDiscover',
         papers=['https://gkhlab.gitlab.io/igdiscover22/'], pdf_urls=[], code_urls=['https://gitlab.com/gkhlab/igdiscover22']),
    dict(id='deepnano', category='identification', name='DeepNano',
         papers=['https://doi.org/10.1038/s42256-024-00940-5'], pdf_urls=['https://www.nature.com/articles/s42256-024-00940-5.pdf'],
         code_urls=['https://github.com/ddd9898/DeepNano']),
    dict(id='nabp_bert', category='identification', name='NABP-BERT',
         papers=['https://academic.oup.com/bib/article/26/1/bbae518/7926359'],
         pdf_urls=['https://academic.oup.com/bib/article-pdf/26/1/bbae518/61287888/bbae518.pdf'],
         code_urls=['https://github.com/FMoonlightS/NABP-BERT']),
    dict(id='abagintpre', category='identification', name='AbAgIntPre',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC9813736/'], pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC9813736/pdf/'],
         code_urls=['https://github.com/emersON106/AbAgIntPre']),
    dict(id='paragraph', category='identification', name='Paragraph',
         papers=['https://academic.oup.com/bioinformatics/article/39/1/btac732/6825310'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/39/1/btac732/48662426/btac732.pdf'],
         code_urls=['https://github.com/oxpig/Paragraph']),
    dict(id='parapred', category='identification', name='ParaPred',
         papers=['https://academic.oup.com/bioinformatics/article/34/17/2944/4972995'],
         pdf_urls=['https://academic.oup.com/bioinformatics/article-pdf/34/17/2944/25721748/bty305.pdf'],
         code_urls=['https://github.com/eliberis/parapred','https://github.com/alchemab/parapred-pytorch']),
    dict(id='sabpred_epipred', category='identification', name='EpiPred / SAbPred',
         papers=['https://academic.oup.com/nar/article/44/W1/W474/2499346'],
         pdf_urls=['https://academic.oup.com/nar/article-pdf/44/W1/W474/17095697/gkw361.pdf'], code_urls=[]),
    dict(id='abadapt', category='identification', name='AbAdapt',
         papers=['https://academic.oup.com/bioinformaticsadvances/article/2/1/vbac015/6543605'],
         pdf_urls=['https://academic.oup.com/bioinformaticsadvances/article-pdf/2/1/vbac015/42893097/vbac015.pdf'], code_urls=[]),
    dict(id='episcan', category='identification', name='EpiScan',
         papers=['https://www.nature.com/articles/s41540-024-00432-7'], pdf_urls=['https://www.nature.com/articles/s41540-024-00432-7.pdf'],
         code_urls=['https://github.com/gzBiomedical/EpiScan']),
    dict(id='imapeP', category='identification', name='ImaPEp',
         papers=['https://www.mdpi.com/1422-0067/25/10/5434'], pdf_urls=['https://www.mdpi.com/1422-0067/25/10/5434/pdf'],
         code_urls=['https://github.com/3BioCompBio/ImaPEp']),

    # Properties / developability
    dict(id='tnp', category='properties', name='TNP / Therapeutic Nanobody Profiler',
         papers=['https://www.nature.com/articles/s42003-026-09594-y'], pdf_urls=['https://www.nature.com/articles/s42003-026-09594-y.pdf'],
         code_urls=['https://github.com/oxpig/TNP']),
    dict(id='aggrescan3d', category='properties', name='Aggrescan3D / A3D 2.0',
         papers=['https://academic.oup.com/nar/article/47/W1/W300/5485072'],
         pdf_urls=['https://academic.oup.com/nar/article-pdf/47/W1/W300/28879756/gkz321.pdf'], code_urls=[]),
    dict(id='camsol', category='properties', name='CamSol',
         papers=['https://www-vendruscolo.ch.cam.ac.uk/camsolmethod.html'], pdf_urls=[], code_urls=[]),
    dict(id='protparam', category='properties', name='ProtParam / Compute pI/Mw',
         papers=['https://web.expasy.org/protparam/','https://web.expasy.org/compute_pi/'], pdf_urls=[], code_urls=[]),
    dict(id='iedb_netmhc', category='properties', name='IEDB / NetMHCIIpan',
         papers=['https://tools.iedb.org/','https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.3/'], pdf_urls=[], code_urls=[]),
    dict(id='tap', category='properties', name='TAP / Therapeutic Antibody Profiler',
         papers=['https://pmc.ncbi.nlm.nih.gov/articles/PMC6410772/','https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabpred/tap'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC6410772/pdf/'], code_urls=[]),
    dict(id='protein_sol_abpred', category='properties', name='Protein-Sol / Abpred',
         papers=['https://protein-sol.manchester.ac.uk/','https://protein-sol.manchester.ac.uk/abpred'], pdf_urls=[], code_urls=[]),
    dict(id='dynamut2', category='properties', name='DynaMut2',
         papers=['https://biosig.lab.uq.edu.au/dynamut2/'], pdf_urls=[], code_urls=[]),
    dict(id='foldx', category='properties', name='FoldX',
         papers=['https://foldxsuite.crg.eu/products','https://pmc.ncbi.nlm.nih.gov/articles/PMC1160148/'],
         pdf_urls=['https://pmc.ncbi.nlm.nih.gov/articles/PMC1160148/pdf/'], code_urls=[]),
    dict(id='solart', category='properties', name='SOLart',
         papers=[], pdf_urls=[], code_urls=[]),
]
